const RECORD_CATEGORIES = Object.freeze([
    ['wins', 'Race wins'],
    ['podiums', 'Podiums'],
    ['poles', 'Pole positions'],
    ['fastestLaps', 'Fastest laps'],
    ['starts', 'Race starts'],
    ['points', 'Points'],
    ['gridGain', 'Average positions gained'],
    ['averageFinish', 'Average finish'],
    ['finishRate', 'Finish rate'],
    ['winRate', 'Win rate'],
    ['podiumRate', 'Podium rate'],
    ['dnfs', 'DNFs'],
    ['championships', 'Championships']
].map(([id, name]) => Object.freeze({ id, name })));

const RECORD_CATEGORY_IDS = new Set(RECORD_CATEGORIES.map(category => category.id));
const ASK_LANGUAGE_POLICY = Object.freeze({
    minimumIntentScore: 0.70,
    ambiguityMargin: 0.025
});

const WEC_INTENT_CATALOG = Object.freeze([
    { id: 'lineup_record', examples: ['Which Hypercar crew scored the most wins together?', 'Which WEC LMP2 crew scored the most points together?'] },
    { id: 'consecutive_event_wins', examples: ['How often did Toyota Gazoo Racing win at consecutive appearances of Le Mans in Hypercar?'] },
    { id: 'team_change_comparison', examples: ['How did Robert Kubica perform before and after joining AF Corse in Hypercar?'] },
    { id: 'compare_seasons', examples: ['How did Robert Kubica perform in 2024 versus 2025 in Hypercar?', 'How did Sébastien Buemi perform in 2023 compared with 2024 in Hypercar?'] },
    { id: 'longest_milestone_gap', examples: ['Who had the longest gap between Hypercar wins?', 'Which driver had the longest gap between WEC podiums in Hypercar?'] },
    { id: 'best_worst_result', examples: ["What was Robert Kubica's best Hypercar season by points?", "What was Robert Kubica's worst WEC race finish?"] },
    { id: 'result_distribution', examples: ["Show Robert Kubica's distribution of finishes in Hypercar", "Show Toyota Gazoo Racing's distribution of points in Hypercar"] },
    { id: 'latest_failure', examples: ['When did Robert Kubica last fail to finish in WEC?', 'When did Toyota Gazoo Racing last fail to score points in Hypercar?'] },
    { id: 'milestone_threshold', examples: ['Which WEC driver reached 10 Hypercar wins in the fewest starts?', 'Who first reached 20 LMP2 podiums?'] },
    { id: 'debut_milestone', examples: ['Who won on debut in Hypercar?', 'Which WEC drivers scored points on debut in LMP2?'] },
    { id: 'milestone_never_reached', examples: ['Which WEC drivers never won despite 20 starts in Hypercar?', 'Who never scored points with 10 starts in LMP2?'] },
    { id: 'team_tenure', examples: ['Who drove for Toyota Gazoo Racing the longest?', 'Which driver spent the longest with Toyota Gazoo Racing?'] },
    { id: 'team_seasons', examples: ['Who spent the most WEC seasons with one team?', 'Most seasons with the same WEC team'] },
    { id: 'teammate_events', examples: ['Which WEC teammates raced together for the most events?', 'Longest-running WEC crew pairing'] },
    { id: 'debut_to_milestone', examples: ['Who took the longest from WEC debut to first win?', 'Longest wait from debut to first WEC podium'] },
    { id: 'standings_gap', examples: ['Smallest points gap between P3 and P4 in final Hypercar standings?', 'Largest P1 to P2 final Hypercar championship gap?'] },
    { id: 'season_standings_gap', examples: ['What was the P3 to P4 gap in 2024 Hypercar final standings?', 'How many points separated P1 and P2 in the 2025 WEC Hypercar championship?'] },
    { id: 'top_four_spread', examples: ['Which Hypercar season had the tightest top four?', 'Tightest top four in final Hypercar standings'] },
    { id: 'latest_team_milestone', examples: ['When did Toyota Gazoo Racing last win a WEC race?', 'When did Ferrari last reach a WEC podium?'] },
    { id: 'points_without_win', examples: ['Who scored the most Hypercar points without a win in a season?', 'Most WEC season points without a race win'] },
    { id: 'season_opener', examples: ['Where was the first WEC race of 2025 held?', 'What was the 2024 WEC season opener?'] },
    { id: 'season_closer', examples: ['What was the last WEC race of 2025?', 'Where did the 2024 WEC season end?'] },
    { id: 'season_calendar', examples: ['List the 2025 WEC race calendar', 'Show every completed WEC event in 2024'] },
    { id: 'season_event_count', examples: ['How many WEC events took place in 2025?', 'How many WEC races were run in 2024?'] },
    { id: 'adjacent_event', examples: ['What came after Spa in the 2025 WEC calendar?', 'Which race preceded Le Mans in 2024?'] },
    { id: 'calendar_host_years', examples: ['Which years did Spa host WEC?', 'In which seasons did the 24 Hours of Le Mans appear?'] },
    { id: 'calendar_host_boundary', examples: ['When did Spa first host WEC?', 'When was the 24 Hours of Le Mans last held?'] },
    { id: 'calendar_host_leader', examples: ['Which WEC circuit hosted the most races?', 'Which WEC event hosted the most races?'] },
    { id: 'driver_debut', examples: ['When did Robert Kubica make his WEC debut?', 'Where was a driver’s first WEC race?'] },
    { id: 'driver_last_start', examples: ['When did Robert Kubica last race in WEC?', 'What was Kubica’s last WEC start?'] },
    { id: 'team_boundary_start', examples: ['When did Toyota Gazoo Racing first start a WEC race?', 'What was Toyota Gazoo Racing’s last WEC start?'] },
    { id: 'competitor_milestone', examples: ['When did Robert Kubica first win in WEC?', 'When did Toyota Gazoo Racing last reach a WEC podium?'] },
    { id: 'latest_team_points', examples: ['When did Toyota Gazoo Racing last score WEC points?', 'What was the last time a WEC team scored points?'] },
    { id: 'record_leader', examples: ['Most Hypercar wins at Spa in 2024', 'Who has the most WEC wins since 2020?'] },
    { id: 'record_subject_total', examples: ['How many LMP2 podiums does Robert Kubica have?', 'How many WEC starts did Toyota make?'] },
    { id: 'head_to_head', examples: ['Toyota versus Ferrari for Hypercar wins', 'Compare Porsche with Toyota for podiums at Le Mans'] },
    { id: 'season_summary', examples: ['Robert Kubica Hypercar season summary in 2024', 'Toyota Hypercar season stats in 2025'] },
    { id: 'season_standings', examples: ['Hypercar driver standings after round 3 in 2025', 'Who won the 2025 Hypercar drivers championship?'] },
    { id: 'race_result', examples: ['Who won the 2025 24 Hours of Le Mans?', 'Show the Hypercar podium at Spa in 2024'] },
    { id: 'wec_class_overall_rank', examples: ['Where did car #51 finish in class and overall at Le Mans in 2024?', 'What were the class and overall positions of car #8 at Spa in 2024?'] },
    { id: 'wec_team_car_count', examples: ['How many cars did Porsche Penske Motorsport enter at Le Mans in 2024?', 'How many cars did Toyota Gazoo Racing enter in the 2024 WEC season?'] },
    { id: 'driver_team_history', examples: ["Which teams did Robert Kubica race for in WEC?", "Who were Robert Kubica's WEC crew partners?"] }
].map(intent => Object.freeze({ ...intent, examples: Object.freeze(intent.examples) })));

const INTENT_CATALOG = Object.freeze([
    { id: 'lineup_record', label: 'most wins or points by a lineup', family: 'archive_facts',
        requiredSlots: ['recordCategory'], optionalSlots: [],
        description: 'Rank stable multi-driver team or WEC car crews by recorded race wins or points.',
        examples: ['Which lineup scored the most wins together?', 'Which lineup scored the most points together?', 'Which driver pair scored the most race wins together?', 'Which crew scored the most points together?'] },
    { id: 'consecutive_event_wins', label: 'consecutive wins at one named event', family: 'archive_facts',
        requiredSlots: ['subjectName', 'eventName'], optionalSlots: ['entity'],
        description: 'Count consecutive winning pairs and runs among a competitor’s appearances of one event.',
        examples: ['How often did Lewis Hamilton win at consecutive appearances of Monaco?', 'How many consecutive appearances at Monaco did Lewis Hamilton win?', 'How often did Ferrari win at consecutive appearances of Monza?', 'How often did Max Verstappen win at consecutive appearances of Spa?'] },
    { id: 'team_change_comparison', label: 'driver results before and after a team change', family: 'archive_facts',
        requiredSlots: ['subjectName', 'newTeamName'], optionalSlots: ['targetSeason'],
        description: 'Compare a driver’s immediately preceding team stint with the selected new-team stint.',
        examples: ['How did Lewis Hamilton perform before and after joining Mercedes?', 'How did Fernando Alonso perform before and after moving to Aston Martin?', 'How did Carlos Sainz perform before and after switching to Ferrari?', 'How did Max Verstappen perform before and after joining Red Bull?'] },
    { id: 'compare_seasons', label: 'same competitor across two seasons', family: 'archive_facts',
        requiredSlots: ['subjectName', 'fromYear', 'toYear'], optionalSlots: ['entity'],
        description: 'Compare recorded starts, wins, podiums and final standings for one competitor in two completed seasons.',
        examples: ['How did Lewis Hamilton perform in 2021 versus 2022?', 'How did Fernando Alonso perform in 2022 compared with 2023?', 'How did Ferrari perform in 2023 and 2024?', 'How did Max Verstappen perform in 2020 vs 2021?'] },
    { id: 'longest_milestone_gap', label: 'longest gap between driver milestones', family: 'archive_facts',
        requiredSlots: ['milestone', 'gapMeasure'], optionalSlots: [],
        description: 'Rank gaps between consecutive wins, podiums, points finishes or starts by calendar days or intervening starts.',
        examples: ['Who had the longest gap between wins?', 'Who had the longest gap between podiums?', 'Which driver had the longest gap between points?', 'Who had the longest gap between race starts?'] },
    { id: 'best_worst_result', label: 'driver best or worst season or race result', family: 'archive_facts',
        requiredSlots: ['subjectName', 'resultMetric', 'extreme'], optionalSlots: [],
        description: 'Rank one driver’s classified race finishes or official final season points or rank.',
        examples: ["What was driver Lewis Hamilton's best season by points?", "What was Fernando Alonso's worst race finish?", "What was Max Verstappen's best season by championship rank?", "What was driver Charles Leclerc's worst season by points?"] },
    { id: 'result_distribution', label: 'competitor finish or race-points distribution', family: 'archive_facts',
        requiredSlots: ['subjectName', 'distributionMetric'], optionalSlots: ['targetSeason', 'entity'],
        description: 'Count recorded starts by finishing position or race-result points.',
        examples: ["Show Lewis Hamilton's distribution of finishes", "What is Fernando Alonso's distribution of points?", 'Show the points distribution for Ferrari in 2024', "What was Max Verstappen's breakdown of finishing positions?"] },
    { id: 'latest_failure', label: 'latest non-scoring race or non-finish', family: 'archive_facts',
        requiredSlots: ['subjectName', 'failureMetric'], optionalSlots: ['entity'],
        description: 'Find the latest recorded start at which a driver or all team starters failed to score or finish.',
        examples: ['When did Lewis Hamilton last fail to score points?', 'When did Ferrari last fail to finish?', 'Where did Fernando Alonso last fail to finish?', 'When did McLaren last fail to score?'] },
    { id: 'driver_season_participation', label: 'driver entered, started, or missed season races', family: 'archive_facts',
        requiredSlots: ['subjectName', 'targetSeason', 'participationMode'], optionalSlots: [],
        description: 'Compare one F1 driver’s recorded race-result entries with the completed season calendar.',
        examples: ['Which races did Alonso miss in 2024?', 'Which events did Alonso enter in 2024?', 'Which races did Alonso start in 2024?', 'Which 2024 races did Alonso start?'] },
    { id: 'driver_team_history', label: 'driver team changes or teammate pairings', family: 'archive_facts',
        requiredSlots: ['subjectName', 'historyMode'], optionalSlots: [],
        description: 'Trace team stints or count teammate pairings from shared recorded starts.',
        examples: ['Which teams did Alonso race for?', "Show Hamilton's team changes", "Who were Alonso's teammates?", "List Hamilton's teammates"] },
    { id: 'round_standings_change', label: 'competitor change between two rounds', family: 'archive_facts',
        requiredSlots: ['subjectName', 'targetSeason', 'roundStart', 'roundEnd'], optionalSlots: ['entity'],
        description: 'Compare official cumulative points and rank after two exact F1 rounds.',
        examples: ["How did Hamilton's championship position change between rounds 3 and 8 of 2021?", "What was Leclerc's points change from round 5 to 10 in 2022?", "How did team Ferrari's rank change between rounds 4 and 9 of 2023?", "What was Norris's standing change from round 2 to 6 in 2024?"] },
    { id: 'round_rival_swing', label: 'points swing between rivals in one round', family: 'archive_facts',
        requiredSlots: ['subjectNames', 'targetSeason', 'standingRound'], optionalSlots: ['entity'],
        description: 'Compare two competitors’ cumulative standings change over one F1 round.',
        examples: ['How many points did Leclerc gain on Verstappen in round 8 of 2022?', 'How many points did Hamilton lose to Rosberg in round 5 of 2016?', 'How many points did team Ferrari gain on team McLaren in round 10 of 2024?', 'How many points did Norris gain against Piastri in round 9 of 2024?'] },
    { id: 'championship_lead_changes', label: 'championship lead changes', family: 'archive_facts',
        requiredSlots: ['targetSeason'], optionalSlots: ['entity'],
        description: 'Count changes in official P1 standings after each F1 round.',
        examples: ['When did the championship lead change in 2021?', 'How often did the driver championship lead change in 2016?', 'Show the team championship lead changes in 2024.', 'When did the constructor championship lead change in 2023?'] },
    { id: 'champion_season_extreme', label: 'fewest or most wins or points by a champion', family: 'archive_facts',
        requiredSlots: ['recordCategory'], optionalSlots: ['entity', 'extreme'],
        description: 'Compare title-winning seasons by recorded race wins or official championship points.',
        examples: ['Which champion had the fewest wins?', 'Which champion scored the most points?', 'Which constructor champion had the most wins?', 'Which driver champion had the least points?'] },
    { id: 'single_season_record', label: 'single-season wins, podiums, poles, or points record', family: 'archive_facts',
        requiredSlots: ['recordCategory'], optionalSlots: ['entity'],
        description: 'Find the highest completed-season total for one recorded metric.',
        examples: ['Who had the most wins in a single season?', 'Who scored the most points in one season?', 'Which driver took the most poles in a single season?', 'Which team had the most podiums in one season?'] },
    { id: 'team_season_extreme', label: 'team best or worst season by metric', family: 'archive_facts',
        requiredSlots: ['subjectName', 'recordCategory'], optionalSlots: ['extreme'],
        description: 'Find a named team’s highest or lowest completed-season wins, podiums, or points.',
        examples: ["What was Ferrari's best season by wins?", "What was Ferrari's worst season by points?", "Show McLaren's most successful season by podiums", "Which was Williams's least successful season by wins?"] },
    { id: 'standings_improvement', label: 'largest change between consecutive final standings', family: 'archive_facts',
        requiredSlots: ['fromYear', 'toYear'], optionalSlots: ['entity'],
        description: 'Compare final championship ranks for competitors present in two consecutive seasons.',
        examples: ['Which driver improved most in the standings from 2023 to 2024?', 'Which team gained the most championship places from 2022 to 2023?', 'Who climbed most positions in the standings between 2020 and 2021?', 'Which constructor improved most in championship rank from 2021 to 2022?'] },
    { id: 'grid_position', label: 'official starting-grid position', family: 'archive_facts', requiredSlots: ['targetSeason', 'eventName', 'resultPosition'], optionalSlots: [],
        description: 'Find the driver at one official starting-grid position after grid penalties.',
        examples: ['Who lined up P3 at Monaco in 2024?', 'Who started from P3 at Monaco in 2024?', 'Which driver occupied grid P3 at Monaco in 2024?', 'Who started from 3rd at Monaco in 2024?'] },
    { id: 'race_pole', label: 'race weekend pole', family: 'archive_facts', requiredSlots: ['targetSeason', 'eventName'], optionalSlots: [],
        description: 'Look up the recorded official pole attribution.',
        examples: ['Who took pole at Monaco in 2024?', 'Who claimed pole for the 2024 Monaco Grand Prix?', 'Which driver was on pole at Monaco in 2024?', 'Who was credited with pole at Monaco in 2024?'] },
    { id: 'session_classification', label: 'race weekend session classification', family: 'archive_facts', requiredSlots: ['targetSeason', 'eventName', 'sessionType'], optionalSlots: [],
        description: 'Show the recorded qualifying, sprint, or main-race classification.',
        examples: ['What was the sprint result at Monaco in 2024?', 'Show the qualifying classification at Monaco in 2024.', 'What happened in the sprint at Monaco in 2024?', 'Show the sprint finishing order at Monaco in 2024.'] },
    { id: 'event_points', label: 'points awarded at an event', family: 'archive_facts', requiredSlots: ['targetSeason', 'eventName'], optionalSlots: ['subjectName', 'entity'],
        description: 'Add main-race and sprint points for one competitor or every competitor.',
        examples: ['How many points did Leclerc score at Monaco in 2024?', "What was Ferrari's points haul at Monaco in 2024?", 'Break down the points from Monaco in 2024.', 'Show every team’s event points at Monaco in 2024.'] },
    { id: 'race_status', label: 'non-finish race statuses', family: 'archive_facts', requiredSlots: ['targetSeason', 'eventName', 'statusFilter'], optionalSlots: ['sessionType'],
        description: 'List retired, non-starting, or disqualified competitors from an exact session.',
        examples: ['Who failed to finish Monaco in 2024?', 'Which entrants were DNS at Monaco in 2024?', 'Who was disqualified at Monaco in 2024?', 'Who retired at Monaco in 2024?'] },
    { id: 'grid_movement', label: 'grid to finish position change', family: 'archive_facts', requiredSlots: ['targetSeason', 'eventName'], optionalSlots: ['extreme'],
        description: 'Rank grid-to-finish place gains or losses among classified starters.',
        examples: ['Who gained most places at Monaco in 2024?', 'Who lost most positions at Monaco in 2024?', 'Which driver gained the most places at Monaco in 2024?', 'Which driver lost the most positions at Monaco in 2024?'] },
    { id: 'race_entries', label: 'event entrants or starters', family: 'archive_facts', requiredSlots: ['targetSeason', 'eventName'], optionalSlots: ['entryMode'],
        description: 'List recorded event entries or actual race starters.',
        examples: ['Who started Monaco in 2024?', 'Show the entry list for Monaco in 2024.', 'Which entrants appeared at Monaco in 2024?', 'Who started at Monaco in 2024?'] },
    { id: 'fastest_race_lap', label: 'fastest lap in a race', family: 'archive_facts', requiredSlots: ['targetSeason', 'eventName'], optionalSlots: [],
        description: 'Read the fastest official race-lap row with driver, lap, and time.',
        examples: ['Who set the fastest race lap at Monaco in 2024?', 'Which driver recorded the fastest lap at Monaco in 2024?', 'Who had the quickest race lap at Monaco in 2024?', 'Who set the fastest lap for Monaco in 2024?'] },
    { id: 'qualifying_position', label: 'qualifying classification position', family: 'archive_facts', requiredSlots: ['targetSeason', 'eventName', 'resultPosition'], optionalSlots: [],
        description: 'Find the recorded qualifying position before grid penalties.',
        examples: ['Who qualified P3 at Monaco in 2024?', 'Which driver qualified P2 at Monaco in 2024?', 'Who was P4 in qualifying at Monaco in 2024?', 'Who took P5 in qualifying at Monaco in 2024?'] },
    { id: 'streak_subject', label: 'one driver’s longest streak', family: 'archive_streaks',
        requiredSlots: ['subjectName', 'streakCategory'], optionalSlots: ['fromYear', 'toYear'],
        description: 'Find a named driver’s longest run and list every event in it.',
        examples: ["What is Hamilton's longest points streak?", "When did Hamilton's longest podium run begin and end?", "List the events in Hamilton's longest win streak.", 'How many consecutive races did Hamilton win at best?'] },
    { id: 'milestone_threshold', label: 'career milestone threshold', family: 'archive_facts', requiredSlots: ['milestone', 'milestoneCount'], optionalSlots: ['chronologyDirection'],
        description: 'Find who first or fastest reached a cumulative win, podium, points, or start threshold.',
        examples: ['Who needed the fewest starts to reach 10 wins?', 'Which driver reached 10 podiums in the fewest starts?', 'Who reached 100 points fastest?', 'Who reached 100 starts first?'] },
    { id: 'debut_milestone', label: 'debut points, podiums, or wins', family: 'archive_facts', requiredSlots: ['milestone'], optionalSlots: [],
        description: 'List drivers whose first recorded race start met the selected milestone.',
        examples: ['Who won on debut?', 'Which drivers scored points on debut?', 'Who reached the podium in their debut race?', 'Who scored points in their first start?'] },
    { id: 'milestone_never_reached', label: 'milestone never reached after starts', family: 'archive_facts', requiredSlots: ['milestone', 'minStarts'], optionalSlots: [],
        description: 'List drivers with a minimum number of recorded starts and no selected milestone.',
        examples: ['Which drivers never won despite 100 starts?', 'Who never scored points with 20 race starts?', 'Which drivers had no podium after 50 starts?', 'Who has the most starts without a win?'] },
    { id: 'team_tenure', label: 'longest team tenure', family: 'archive_facts', requiredSlots: ['subjectName'], optionalSlots: [],
        description: 'Rank drivers by summed calendar time across separate stints with a named team.',
        examples: ['Who drove for Ferrari the longest?', 'Which driver was with McLaren for the longest time?', 'Who spent the longest driving for Williams?', 'Longest-serving driver for Mercedes?'] },
    { id: 'team_seasons', label: 'most seasons with one team', family: 'archive_facts', requiredSlots: [], optionalSlots: [],
        description: 'Count distinct seasons for every driver-team pair.',
        examples: ['Who spent the most seasons with one team?', 'Which driver raced the most seasons for the same team?', 'Most seasons with one constructor', 'Who has driven for a single team in the most seasons?'] },
    { id: 'teammate_events', label: 'most shared teammate events', family: 'archive_facts', requiredSlots: [], optionalSlots: [],
        description: 'Count events at which both drivers started for the same team.',
        examples: ['Which teammates raced together for the most events?', 'Who were teammates for the most race weekends?', 'Which driver pair shared a team at the most events?', 'Most events raced together as teammates'] },
    { id: 'debut_to_milestone', label: 'debut to first milestone', family: 'archive_facts', requiredSlots: ['milestone'], optionalSlots: ['extreme', 'milestoneMeasure'],
        description: 'Rank calendar time or race starts from first start to first points, podium or win.',
        examples: ['Who took the longest from debut to first points?', 'Longest wait from debut to first podium', 'Which driver waited longest for a first win after debut?', 'Who reached a first win in the fewest starts?'] },
    { id: 'standings_gap', label: 'final standings points gap', family: 'archive_facts', requiredSlots: ['firstPosition', 'secondPosition'], optionalSlots: ['entity', 'extreme'],
        description: 'Find the largest or smallest final points gap between any two standings positions.',
        examples: ['What is the smallest points gap between P3 and P4 in final standings?', 'Largest final points gap between P2 and P5', 'Closest final championship margin between P1 and P2', 'What was the widest gap from P1 to P4 in final driver standings?'] },
    { id: 'season_standings_gap', label: 'one-season final standings gap', family: 'archive_facts', requiredSlots: ['targetSeason', 'firstPosition', 'secondPosition'], optionalSlots: ['entity'],
        description: 'Subtract two official final standings points totals in one completed season.',
        examples: ['What was the P3 to P4 points gap in the 2024 final standings?', 'How many points separated P1 and P2 in the 2025 drivers championship?', 'What was the P1 to P2 margin in 2024 final standings?', 'How many points separated P2 and P5 in the 2023 final team standings?'] },
    { id: 'top_four_spread', label: 'tightest final top four', family: 'archive_facts', requiredSlots: [], optionalSlots: ['entity'],
        description: 'Find the smallest P1 to P4 points spread in completed seasons.',
        examples: ['Which season had the tightest top four in final standings?', 'Closest top four in the final championship table', 'Which year had the narrowest top four points spread?', 'Tightest final top four drivers'] },
    { id: 'latest_team_milestone', label: 'latest team podium or win', family: 'archive_facts', requiredSlots: ['subjectName', 'milestone'], optionalSlots: [],
        description: 'Find the latest recorded podium or win by a named team.',
        examples: ['When did Ferrari last win?', 'When did Alpine last reach a podium?', 'What was the last time McLaren won a race?', 'Most recent podium for Williams'] },
    { id: 'points_without_win', label: 'most season points without a win', family: 'archive_facts', requiredSlots: [], optionalSlots: [],
        description: 'Rank completed driver seasons with zero race wins by official points.',
        examples: ['Who scored the most points without winning a race in a season?', 'Most season points with no win', 'Which driver had the highest points total without a victory?', 'Who scored the most championship points in a winless season?'] },
    {
        id: 'record_leader',
        label: 'a record ranking',
        family: 'archive_records',
        requiredSlots: ['recordCategory'],
        optionalSlots: ['entity', 'constructorName', 'circuitName', 'venueCountryName', 'nationalityName', 'raceFormat', 'resultLimit', 'minStarts', 'fromYear', 'toYear'],
        description: 'Rank drivers or constructors by an official career record.',
        examples: ['Who has the most race wins?', 'Rank constructors by podiums', 'Which driver holds the pole-position record?', 'Show the top five drivers by fastest laps']
    },
    {
        id: 'record_subject_total',
        label: 'one competitor’s record total',
        family: 'archive_records',
        requiredSlots: ['recordCategory', 'subjectName'],
        optionalSlots: ['entity', 'constructorName', 'circuitName', 'venueCountryName', 'nationalityName', 'raceFormat', 'resultLimit', 'minStarts', 'fromYear', 'toYear'],
        description: 'Calculate one driver or constructor’s official record total.',
        examples: ['How many wins does Lewis Hamilton have?', 'How many podiums did Ferrari score?', "What is Verstappen's win record?", "Alonso's total race starts"]
    },
    {
        id: 'race_result',
        label: 'a race result',
        family: 'archive_facts',
        requiredSlots: ['targetSeason', 'eventName'],
        optionalSlots: ['targetSeason', 'eventName', 'raceId', 'subjectName', 'subjectId', 'resultView', 'raceFormat'],
        description: 'Look up a race winner, podium, classification, or one driver’s result.',
        examples: ['Who won the 2024 Monaco Grand Prix?', 'Who was on the podium at the British Grand Prix in 2023?', 'Show the classification at the 2022 Italian Grand Prix', 'Where did Alonso finish at the 2021 Hungarian Grand Prix?', 'Show the finishing order from Monaco in 2022']
    },
    {
        id: 'season_opener', label: 'the first race of a season', family: 'archive_facts',
        requiredSlots: ['targetSeason'], optionalSlots: [],
        description: 'Find the first recorded race and its location in a season.',
        examples: ['Where was the first Grand Prix of 2025 held?', 'Where did the 2024 season opener take place?', 'What was the opening race of 2023?', 'Which circuit hosted the first Grand Prix in 2022?']
    },
    { id: 'season_closer', label: 'the last completed race of a season', family: 'archive_facts',
        requiredSlots: ['targetSeason'], optionalSlots: [],
        description: 'Find the last completed race and its location in a season.',
        examples: ['What was the last Grand Prix of 2025?', 'Where did the 2024 season finish?', 'Where was the final race of 2025?', 'What was the last race of the 2023 season?'] },
    { id: 'season_calendar', label: 'a completed season calendar', family: 'archive_facts',
        requiredSlots: ['targetSeason'], optionalSlots: [],
        description: 'List a season’s completed events in round order.',
        examples: ['Show the completed 2025 race calendar', 'List every event held in the 2024 season', 'List all races in the 2024 calendar', 'Show the events on the 2025 race calendar'] },
    { id: 'season_event_count', label: 'a season event or race count', family: 'archive_facts',
        requiredSlots: ['targetSeason', 'countUnit'], optionalSlots: [],
        description: 'Count completed events or recorded race sessions in a season.',
        examples: ['How many events took place in 2025?', 'How many races were run in the 2024 season?', 'How many races took place in 2025?', 'How many events did the 2024 season have?'] },
    { id: 'adjacent_event', label: 'the next or previous event', family: 'archive_facts',
        requiredSlots: ['targetSeason', 'eventName', 'calendarDirection'], optionalSlots: [],
        description: 'Find the event immediately before or after a named completed event in one season.',
        examples: ['What came after Monaco in the 2025 calendar?', 'Which race preceded Spa in 2024?', 'What came before Spa in the 2024 calendar?', 'What race followed Monaco in 2025?'] },
    { id: 'calendar_host_years', label: 'calendar years for one circuit or event', family: 'archive_facts',
        requiredSlots: ['calendarHistoryName', 'calendarHistoryKind'], optionalSlots: [],
        description: 'List completed seasons in which a circuit or named event appears.',
        examples: ['Which years did Spa host Formula 1?', 'In which seasons did the Monaco Grand Prix appear?', 'What years did Silverstone host Formula 1?', 'Which seasons did the British Grand Prix appear on the calendar?'] },
    { id: 'calendar_host_boundary', label: 'first or last calendar appearance', family: 'archive_facts',
        requiredSlots: ['calendarHistoryName', 'calendarHistoryKind', 'chronologyDirection'], optionalSlots: [],
        description: 'Find the first or last recorded appearance of one circuit or event.',
        examples: ['When did Spa first host Formula 1?', 'When was the Monaco Grand Prix last held?', 'When did Silverstone last host Formula 1?', 'What was the British Grand Prix’s first calendar appearance?'] },
    { id: 'calendar_host_leader', label: 'circuit or event with most races', family: 'archive_facts',
        requiredSlots: ['calendarHistoryKind'], optionalSlots: [],
        description: 'Rank circuits or named events by completed classified races.',
        examples: ['Which circuit hosted the most races?', 'Which event hosted the most races?', 'Which venue hosted the most races?', 'Which Grand Prix hosted the most races?'] },
    {
        id: 'driver_debut', label: 'a driver debut', family: 'archive_facts',
        requiredSlots: ['subjectName'], optionalSlots: [],
        description: 'Find a driver’s first recorded race start in this championship.',
        examples: ['When did Schumacher make his debut?', 'Where did Hamilton make his debut?', 'What year did Alonso make his debut?', 'Which race was Vettel’s debut?', 'When did Prost debut?', 'When did Prost first race?', 'Prost debut date']
    },
    { id: 'driver_last_start', label: 'a driver’s last recorded start', family: 'archive_facts',
        requiredSlots: ['subjectName'], optionalSlots: [],
        description: 'Find a driver’s last recorded race start.',
        examples: ['When did Prost last race?', 'What was Alonso’s final recorded start?', 'When was Prost’s last recorded race?', 'What was Hamilton’s final start?'] },
    { id: 'team_boundary_start', label: 'a team’s first or last start', family: 'archive_facts',
        requiredSlots: ['subjectName', 'chronologyDirection'], optionalSlots: [],
        description: 'Find a team’s first or last recorded race start.',
        examples: ['When did the Ferrari team first race?', 'What was the Williams team’s last recorded start?', 'When did the McLaren team make its first start?', 'When was the Williams team’s final race?'] },
    { id: 'competitor_milestone', label: 'a competitor’s first or last milestone', family: 'archive_facts',
        requiredSlots: ['subjectName', 'chronologyDirection', 'milestone'], optionalSlots: ['entity'],
        description: 'Find a driver or team’s first or last points, podium or win result.',
        examples: ['When did Prost first win?', 'When did Alpine first reach a podium?', 'What was Hamilton’s first points finish?', 'What was Prost’s last win?'] },
    { id: 'competitor_season_summary', label: 'one competitor’s season summary', family: 'archive_facts',
        requiredSlots: ['targetSeason', 'subjectName'], optionalSlots: ['entity'],
        description: 'Summarize a competitor’s starts, wins, podiums, official points, and final position in one completed season.',
        examples: ['Show the 2024 season stats for Charles Leclerc', 'Give me the 2023 season summary for Fernando Alonso', 'Summarize Charles Leclerc’s 2024 season', 'What were Charles Leclerc’s season totals in 2024?'] },
    {
        id: 'latest_team_points', label: 'a team’s latest points finish', family: 'archive_facts',
        requiredSlots: ['subjectName'], optionalSlots: [],
        description: 'Find the latest recorded race or sprint where a team scored championship points.',
        examples: ['What was the last time Alpine scored points?', 'When was the last time Ferrari scored points?', 'What is the most recent race where McLaren scored points?', 'When was the last time Williams earned points?']
    },
    {
        id: 'season_standings',
        label: 'season standings',
        family: 'archive_facts',
        requiredSlots: ['targetSeason'],
        optionalSlots: ['entity', 'standingRound', 'resultLimit'],
        description: 'Show a season championship table, including standings after a round.',
        examples: ['Show the 2024 driver standings', 'Show the 2023 constructor championship table', 'Driver standings after round 10 in 2022', 'Final standings for the 2020 season', 'Season leaderboard for 2024']
    },
    {
        id: 'driver_profile',
        label: 'a driver profile',
        family: 'archive_facts',
        requiredSlots: ['subjectName'],
        optionalSlots: [],
        description: 'Summarize a driver’s identity, career span, teams, results and championships.',
        examples: ['Tell me about Fernando Alonso', 'Who is Lewis Hamilton?', 'Give me a profile of Ayrton Senna', 'Tell me about Sebastian Vettel']
    },
    {
        id: 'constructor_profile',
        label: 'a constructor profile',
        family: 'archive_facts',
        requiredSlots: ['subjectName'],
        optionalSlots: [],
        description: 'Summarize a constructor or team’s history, drivers, results and championships.',
        examples: ['Tell me about the Ferrari team', 'Give me a constructor profile of McLaren', 'Who drove for Williams?', 'What is the Red Bull Racing team?']
    },
    {
        id: 'circuit_profile',
        label: 'a circuit profile',
        family: 'archive_facts',
        requiredSlots: ['circuitName'],
        optionalSlots: [],
        description: 'Summarize a circuit, its location, archive history and most frequent winners.',
        examples: ['Tell me about the Monaco circuit', 'Give me a profile of Silverstone track', 'What is the Spa-Francorchamps circuit?', 'Tell me about the Monza circuit']
    },
    {
        id: 'season_summary',
        label: 'a season summary',
        family: 'archive_facts',
        requiredSlots: ['targetSeason'],
        optionalSlots: [],
        description: 'Summarize a season’s champions, races, winners and leading standings.',
        examples: ['Summarize the 2012 season', 'What happened in the 2021 season?', 'Give me an overview of the 2008 season', 'Who were the 2023 champions?']
    },
    {
        id: 'motorsport_explanation',
        label: 'a motorsport explanation',
        family: 'knowledge',
        requiredSlots: ['topic'],
        optionalSlots: [],
        description: 'Explain a supported motorsport term or a Racelytic methodology concept.',
        examples: ['What is countback?', 'Explain the undercut', 'How does DRS work?', 'What does classified mean?']
    },
    {
        id: 'driver_head_to_head',
        label: 'a driver comparison',
        family: 'comparisons',
        requiredSlots: ['subjectNames'],
        minimumItems: { subjectNames: 2 },
        optionalSlots: ['subjectIds', 'comparisonScope', 'comparisonMetric', 'pointsSystemYear', 'constructorName', 'circuitName', 'venueCountryName', 'fromYear', 'toYear'],
        description: 'Compare two drivers across shared starts or their teammate races.',
        examples: ['Compare Hamilton and Verstappen head-to-head', 'Hamilton versus Rosberg in qualifying', 'Who has more wins, Senna or Prost?', 'Compare Alonso with Räikkönen as teammates']
    },
    {
        id: 'constructor_head_to_head',
        label: 'a constructor comparison',
        family: 'comparisons',
        requiredSlots: ['subjectNames'],
        minimumItems: { subjectNames: 2 },
        optionalSlots: ['comparisonMetric', 'circuitName', 'venueCountryName', 'fromYear', 'toYear'],
        description: 'Compare two constructors or teams using official archive totals.',
        examples: ['Compare teams Ferrari and McLaren head-to-head', 'Constructors Ferrari versus McLaren for wins', 'Compare Mercedes and Red Bull constructors in 2021', 'Which team had more points, Ferrari or McLaren?']
    },
    {
        id: 'streak_leader',
        label: 'a streak ranking',
        family: 'archive_streaks',
        requiredSlots: ['streakCategory'],
        optionalSlots: ['fromYear', 'toYear', 'resultLimit'],
        description: 'Rank the longest consecutive win, podium, points or classified-finish streaks.',
        examples: ['Who has the longest winning streak?', 'Most consecutive podiums', 'Show the longest points-scoring streak', 'Most classified finishes in a row']
    },
    {
        id: 'recalculate_title_counts',
        label: 'recalculated career title totals',
        family: 'points_counterfactual',
        requiredSlots: ['entity', 'pointsSystemYear'],
        optionalSlots: ['fromYear', 'toYear'],
        description: 'Rank championship totals under a historical rulebook.',
        examples: ['Who has the most titles under 1982 rules?', 'Rank drivers by championships using 1991 scoring', 'Top constructor by titles with 2010 points', 'Who leads the WDC count under current rules?']
    },
    {
        id: 'recalculate_points_totals',
        label: 'recalculated career points totals',
        family: 'points_counterfactual',
        requiredSlots: ['entity', 'pointsSystemYear'],
        optionalSlots: ['fromYear', 'toYear', 'resultLimit'],
        description: 'Rank cumulative career points after rescoring every completed season with one historical rulebook.',
        examples: ['Who would have the most points if all seasons used the 2024 points system?', 'Rank drivers by career points under 2010 scoring', 'Which constructor scores the most total points with 1991 rules?', 'Top cumulative driver points using current rules']
    },
    {
        id: 'recalculate_season_champion',
        label: 'a recalculated season champion',
        family: 'points_counterfactual',
        requiredSlots: ['entity', 'pointsSystemYear', 'targetSeason'],
        optionalSlots: [],
        description: 'Recalculate one season under a historical rulebook.',
        examples: ['Who wins the 2008 championship under 1991 rules?', 'Which constructor wins the 2016 title using 1982 points?', 'Who would have won the championship in 2021 with 2003 scoring?', 'Why would the 2012 championship be won by Vettel under 2010 rules?']
    },
    {
        id: 'recalculate_entity_titles',
        label: 'one competitor’s recalculated titles',
        family: 'points_counterfactual',
        requiredSlots: ['pointsSystemYear', 'subjectName'],
        optionalSlots: ['entity', 'fromYear', 'toYear'],
        description: 'Recalculate one driver or constructor’s titles.',
        examples: ['How many titles would Alonso have under 1982 rules?', 'How many WDCs does Vettel win with 1991 scoring?', 'How many championships for McLaren under 2010 rules?', 'How many WCCs would Ferrari have under current rules?']
    },
    {
        id: 'list_changed_championships',
        label: 'championships changed by another rulebook',
        family: 'points_counterfactual',
        requiredSlots: ['entity', 'pointsSystemYear'],
        optionalSlots: ['fromYear', 'toYear'],
        description: 'List championships that change under a historical rulebook.',
        examples: ['Which championships change under 1991 rules?', 'What seasons would flip with 1982 scoring?', 'Which WCC champions differ under 2010 points?', 'How many driver championships switch with current rules?']
    },
    {
        id: 'compare_points_systems',
        label: 'a comparison of scoring systems',
        family: 'points_counterfactual',
        requiredSlots: ['comparisonPointsSystemYears'],
        minimumItems: { comparisonPointsSystemYears: 2 },
        optionalSlots: ['entity', 'subjectName', 'fromYear', 'toYear'],
        description: 'Compare two complete historical rulebooks.',
        examples: ['Compare the 1982 and 1991 systems', '1982 rules versus 2010 rules', 'How does Ferrari perform under current rules versus 2003 rules?', 'Does Alonso win more titles under 1982 or 1991 rules?']
    }
].map(intent => Object.freeze({
    ...intent,
    requiredSlots: Object.freeze(intent.requiredSlots),
    optionalSlots: Object.freeze(intent.optionalSlots),
    minimumItems: intent.minimumItems ? Object.freeze(intent.minimumItems) : undefined,
    examples: Object.freeze(intent.examples)
})));

const BY_ID = new Map(INTENT_CATALOG.map(intent => [intent.id, intent]));

function intentDefinition(id) {
    return BY_ID.get(id) || null;
}

function intentLabel(id) {
    return intentDefinition(id)?.label || id;
}

function supportedIntentIds() {
    return new Set(BY_ID.keys());
}

function hasSlotValue(value, minimumItems = 1) {
    if (Array.isArray(value)) return value.filter(item => item !== null && item !== undefined && item !== '').length >= minimumItems;
    return value !== null && value !== undefined && value !== '';
}

function missingRequiredSlots(intentId, slots = {}) {
    const definition = intentDefinition(intentId);
    if (!definition) return [];
    return definition.requiredSlots.filter(slot => !hasSlotValue(slots[slot], definition.minimumItems?.[slot] || 1));
}

function isRecordCategory(value) {
    return RECORD_CATEGORY_IDS.has(value);
}

module.exports = {
    ASK_LANGUAGE_POLICY,
    INTENT_CATALOG,
    WEC_INTENT_CATALOG,
    RECORD_CATEGORIES,
    intentDefinition,
    intentLabel,
    isRecordCategory,
    missingRequiredSlots,
    supportedIntentIds
};
