let recordType='drivers',recordEntries=[],recordPage=1;
const recordTeamLabel = window.location.pathname.startsWith('/f3/') ? 'Team' : 'Constructor';
const recordSeries = window.location.pathname.startsWith('/f3/') ? 'f3' : window.location.pathname.startsWith('/f2/') ? 'f2' : 'f1';
if (recordSeries === 'f3') {
  const teamButton = document.querySelector('[data-record-type="constructors"]');
  if (teamButton) teamButton.textContent = 'Teams';
  const teamLabel = document.querySelector('#record-constructor-label > span');
  if (teamLabel) teamLabel.textContent = 'Team';
  const description = document.querySelector('.analysis-detail-head p');
  if (description) description.textContent = 'Rank Formula 3 drivers and teams across any season, circuit or nationality.';
}
const recordControls=['record-from-year','record-to-year','record-circuit','record-constructor','record-nationality','record-include-sprints'];
function currentRecordConfiguration(){return{series:recordSeries,type:recordType,category:document.getElementById('record-category').value,fromYear:document.getElementById('record-from-year').value||null,toYear:document.getElementById('record-to-year').value||null,circuitId:document.getElementById('record-circuit').value,constructorId:recordType==='drivers'?document.getElementById('record-constructor').value:'',nationality:document.getElementById('record-nationality').value,includeSprints:document.getElementById('record-include-sprints').checked};}
function restoreRecordConfiguration(){const query=params();if(!query.has('type')&&!query.has('category'))return;recordType=query.get('type')==='constructors'?'constructors':'drivers';document.getElementById('record-category').value=query.get('category')||'wins';document.getElementById('record-from-year').value=query.get('fromYear')||'';document.getElementById('record-to-year').value=query.get('toYear')||'';document.getElementById('record-circuit').value=query.get('circuitId')||'';document.getElementById('record-constructor').value=query.get('constructorId')||'';document.getElementById('record-nationality').value=query.get('nationality')||'';document.getElementById('record-include-sprints').checked=query.get('includeSprints')==='true';document.querySelectorAll('[data-record-type]').forEach(button=>button.classList.toggle('active',button.dataset.recordType===recordType));document.getElementById('record-constructor-label').hidden=recordType==='constructors';}
function recordQuery(){const query=new URLSearchParams({type:recordType,category:document.getElementById('record-category').value,limit:'250'}),values={fromYear:document.getElementById('record-from-year').value,toYear:document.getElementById('record-to-year').value,circuitId:document.getElementById('record-circuit').value,constructorId:recordType==='drivers'?document.getElementById('record-constructor').value:'',nationality:document.getElementById('record-nationality').value};Object.entries(values).forEach(([key,value])=>{if(value)query.set(key,value);});if(document.getElementById('record-include-sprints').checked)query.set('includeSprints','true');return query;}
function recordValue(entry,category){return category==='gridGain'?`${entry.value>0?'+':''}${entry.value.toFixed(2)}`:fmtNumber(entry.value);}
function activeFilterLabels(){const labels=[];const from=document.getElementById('record-from-year').value,to=document.getElementById('record-to-year').value;if(from||to)labels.push(`${from||'1950'}–${to||'present'}`);[['record-circuit','Circuit'],['record-constructor',recordTeamLabel],['record-nationality','Nationality']].forEach(([id,label])=>{const select=document.getElementById(id);if(select.value&&(id!=='record-constructor'||recordType==='drivers'))labels.push(`${label}: ${select.options[select.selectedIndex].text}`);});if(document.getElementById('record-include-sprints').checked)labels.push('Sprints included');return labels;}
function renderRecordResults(){const category=document.getElementById('record-category').value,paged=pageItems(recordEntries,recordPage,25);recordPage=paged.page;const link=recordType==='drivers'?'driver':'constructor';document.getElementById('record-categories').innerHTML=recordEntries.length?`<div class="record-ranking"><div class="record-ranking-head"><span>Rank</span><span>${recordType==='drivers'?'Driver':'Constructor'}</span><span>Period</span><span>Starts</span><span>Wins</span><span>Podiums</span><span>${esc(document.getElementById('record-results-title').textContent)}</span></div>${paged.items.map((entry,index)=>`<a href="/${link}?id=${encodeURIComponent(entry.id)}" class="record-ranking-row${paged.start+index<3?' podium-record':''}"><b>${paged.start+index+1}</b><span><strong>${esc(entry.name)}</strong><small>${esc(String(entry.nationalityCountryId||'').toUpperCase())}</small></span><span>${entry.firstYear===entry.lastYear?entry.firstYear:`${entry.firstYear}–${entry.lastYear}`}</span><span>${fmtNumber(entry.starts)}</span><span>${fmtNumber(entry.wins)}</span><span>${fmtNumber(entry.podiums)}</span><em>${recordValue(entry,category)}</em></a>`).join('')}</div>`:'<div class="empty-state">No records match these filters.</div>';renderPagination('record-categories',recordEntries.length,recordPage,25,page=>{recordPage=page;renderRecordResults();document.querySelector('.record-explorer-results').scrollIntoView({behavior:'smooth'});});}
function renderRecordSummary(data){const leaders=data.entries.slice(0,3),link=recordType==='drivers'?'driver':'constructor';document.getElementById('record-explorer-summary').innerHTML=leaders.length?leaders.map((entry,index)=>`<a href="/${link}?id=${encodeURIComponent(entry.id)}"><span>${['Leader','Second','Third'][index]}</span><strong>${esc(entry.name)}</strong><b>${recordValue(entry,data.category)} <small>${esc(data.label)}</small></b></a>`).join(''):'<div class="empty-state">No leaders available.</div>';}
async function loadRecords(){document.getElementById('record-categories').innerHTML='<div class="loading-state">Calculating records…</div>';try{const data=await getJSON(`/api/records/explore?${recordQuery()}`);recordEntries=data.entries;recordPage=1;document.getElementById('record-results-title').textContent=data.label;const filters=activeFilterLabels();document.getElementById('record-results-status').textContent=`${fmtNumber(data.entries.length)} ${recordType} · ${filters.join(' · ')||'All-time'}`;document.getElementById('active-record-filter-count').textContent=filters.length?`${filters.length} active filter${filters.length===1?'':'s'}`:'No filters applied';renderRecordSummary(data);renderRecordResults();}catch(error){setError('record-categories',error.message);}}
function setRecordType(type){recordType=type;document.querySelectorAll('[data-record-type]').forEach(button=>{const active=button.dataset.recordType===type;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});document.getElementById('record-constructor-label').hidden=type==='constructors';loadRecords();}
async function initialiseRecords(){try{const [circuits,constructors,drivers]=await Promise.all([getJSON('/api/circuits'),getJSON('/api/constructors'),getJSON('/api/drivers?limit=1000')]);document.getElementById('record-circuit').insertAdjacentHTML('beforeend',circuits.filter(item=>Number(item.totalRacesHeld)>0).map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join(''));document.getElementById('record-constructor').insertAdjacentHTML('beforeend',constructors.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join(''));const nationalities=[...new Set([...drivers.map(item=>item.nationalityCountryId||item.countryCode),...constructors.map(item=>item.countryId||item.countryCode)].filter(Boolean))].sort();document.getElementById('record-nationality').insertAdjacentHTML('beforeend',nationalities.map(id=>`<option value="${esc(id)}">${esc(String(id).toUpperCase())}</option>`).join(''));restoreRecordConfiguration();loadRecords();}catch(error){setError('record-categories',error.message);}}
document.querySelectorAll('[data-record-type]').forEach(button=>button.addEventListener('click',()=>setRecordType(button.dataset.recordType)));document.getElementById('apply-record-filters').addEventListener('click',loadRecords);document.getElementById('record-category').addEventListener('change',loadRecords);document.getElementById('records-filter-toggle').addEventListener('click',()=>{const panel=document.getElementById('records-advanced-filters'),hidden=panel.hidden;panel.hidden=!hidden;document.getElementById('records-filter-toggle').setAttribute('aria-expanded',String(hidden));});document.getElementById('reset-record-filters').addEventListener('click',()=>{recordControls.forEach(id=>{const element=document.getElementById(id);element.type==='checkbox'?element.checked=false:element.value='';});loadRecords();});
document.getElementById('show-save-record').addEventListener('click',async()=>{const account=await getJSON('/api/account');if(!account.user){window.location.href='/account';return;}const panel=document.getElementById('save-record-panel');panel.hidden=false;document.getElementById('save-record-name').value=`${document.getElementById('record-results-title').textContent} · ${activeFilterLabels().join(' · ')||'All-time'}`;document.getElementById('save-record-name').focus();});document.getElementById('cancel-save-record').addEventListener('click',()=>{document.getElementById('save-record-panel').hidden=true;});document.getElementById('save-record-panel').addEventListener('submit',async event=>{event.preventDefault();const message=document.getElementById('save-record-message');message.textContent='Saving…';try{const response=await fetch('/api/records/saved',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:document.getElementById('save-record-name').value,visibility:document.getElementById('save-record-visibility').value,configuration:currentRecordConfiguration()})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to save record.');message.textContent=data.visibility==='public'?'Saved and shared with the community.':'Saved to your record book.';setTimeout(()=>{document.getElementById('save-record-panel').hidden=true;message.textContent='';},900);}catch(error){message.textContent=error.message;}});
initialiseRecords();
